### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by luckyguy73** [jmatzen/quizsail#10]
First I did npm install to load the node modules.  I then run npm start and get this error.  I don't have docker installed, but not sure if that is even related to this problem.  See screenshot for error details and hopefully this is an easy fix so I can start using this quizsail app.

<img width="1169" alt="Screen Shot 2019-08-03 at 9 53 40 AM" src="https://user-images.githubusercontent.com/18206189/62414774-0f3f9f00-b5d5-11e9-87b5-f77b3abbe468.png">

**Comment by jmatzen** [comment]
Try creating the data directory manually:

`mkdir data`

**Comment by luckyguy73** [comment]
that did the trick, thanks!
