### ISSUE TITLE
Quizsail website gateway routing to wrong site when using unsecured http and older browsers.

### ISSUE THREAD

**Issue by VeraButler** [jmatzen/quizsail#12]
Some students are seeing this when they visit the site: https://media.discordapp.net/attachments/558308722271846410/635147468564070441/image0.jpg?width=324&height=702 

I think it may be a https thing? When they click the direct link https://www.quizsail.com it works fine.

**Comment by jmatzen** [comment]
Thanks for letting me know. It’s not hacked looks like a configuration issue. There’s a ChessCorp server running on my back-end and for some reason the gateway is routing into it. Will try to get it fixed today.
