### ISSUE TITLE
Progress is lost if user doesn't save the URL

### ISSUE THREAD

**Issue by qualitymanifest** [jmatzen/quizsail#14]
As far as I can tell the only way to continue where you left off is if you save a copy of the URL somewhere. It would be good if, when visiting the home page, the user could see a list of their  sessions and select one to continue.

Seems like an easy way to solve this would be to put their query strings (possibly along with "created on" and "last used" dates) into localstorage, whenever a new session is created. Then when they visit the homepage, check their localstorage and display a list of links with dates. 

It wouldn't help if the user moves to a different device, but to solve that you'd have to implement users with authentication and everything, which is probably overkill.

Anyway if this sounds good I could send a PR with these changes. Thanks for making this, it's very helpful.

**Comment by jmatzen** [comment]
I've thought about something like this.  It hasn't been a huge ask but if you see some value in it then go for it.

**Comment by qualitymanifest** [comment]
Sounds good, I'll probably go ahead. Quick question then: Do sessions persist indefinitely on the server or are they deleted at some point? It seems like they would be lost whenever a new deployment is made - right?

**Comment by jmatzen** [comment]
They persist in flat files on the server.  They would only get lost if you deleted them or moved the server and didn't move the files.  So maybe someday I'd run a process that would delete them if they were so old but they're not that big and it's not exactly getting a million monthly users :).

**Comment by jmatzen** [comment]
fwiw I finally recovered the password on the server and deployed this version!
