### ISSUE TITLE
C191 questions and answers need to be double checked

### ISSUE THREAD

**Issue by tmaclea** [jmatzen/quizsail#19]
Many of the answers to the questions for C191 are wrong and directly contradict the Wiley textbook. I am about halfway through the 705 questions and I have found about a dozen definitely-wrong answers. Many of the questions I can't find a reference for because they are not found in the textbook and they need to be double checked because studying from incorrect reference material is unacceptable. I am just a student so if it's possible to get a professor to check the questions, that would be ideal. 
I will attach the incorrect answers I found so far as images with the text to prove they are wrong. I will add the incorrect ones I find in the second half later on.

![incorrect1](https://user-images.githubusercontent.com/12616028/84832713-a1307a80-afe2-11ea-9adb-64d4d46f585f.png)
![incorrect2](https://user-images.githubusercontent.com/12616028/84832718-a4c40180-afe2-11ea-9970-0306b67775ca.png)
![incorrect3](https://user-images.githubusercontent.com/12616028/84832722-a68dc500-afe2-11ea-9b15-3867953d2bff.PNG)
![incorrect4](https://user-images.githubusercontent.com/12616028/84832728-a988b580-afe2-11ea-8122-e9e8884c044e.png)
![incorrect5](https://user-images.githubusercontent.com/12616028/84832730-abeb0f80-afe2-11ea-92e9-b089c181e506.png)
![incorrect6](https://user-images.githubusercontent.com/12616028/84832736-ae4d6980-afe2-11ea-84a2-28c4ff61d038.png)
![incorrect7](https://user-images.githubusercontent.com/12616028/84832741-b0172d00-afe2-11ea-82c5-cef2d7e95faf.png)
![incorrect8](https://user-images.githubusercontent.com/12616028/84832749-b1e0f080-afe2-11ea-8f9d-baa5967f2829.png)
![incorrect9](https://user-images.githubusercontent.com/12616028/84832756-b4dbe100-afe2-11ea-8b38-6d64425824a3.png)
![incorrect10](https://user-images.githubusercontent.com/12616028/84832761-b6a5a480-afe2-11ea-9c7b-ee53d7358e05.png)
![incorrect11](https://user-images.githubusercontent.com/12616028/84832770-b907fe80-afe2-11ea-8fa7-f6c06791d1e1.png)
![incorrect12](https://user-images.githubusercontent.com/12616028/84832773-bad1c200-afe2-11ea-9da9-3075f9dc4a71.png)
![incorrect13](https://user-images.githubusercontent.com/12616028/84832781-bc9b8580-afe2-11ea-9877-85578f309099.png)

**Comment by drewwmercer** [comment]
@tmaclea you might not be aware that this is not distributed by WGU nor is it required that you study with this tool. This was created by students looking to help each other out, and as you can see it is open source and open to contributions. I'm sure contributions and edits are welcome but your tone is pretty aggressive considering someone put in the time to make these 700+ questions available to you.

**Comment by tmaclea** [comment]
@drewwmercer You're right, I apologize for the aggressive tone. I think to tool is great, and I'm happy to make the PR for the questions that I can verify are wrong.
