### ISSUE TITLE
Blank Screen for Course C191

### ISSUE THREAD

**Issue by kshaw75** [jmatzen/quizsail#25]
I had the blank screen appear on Monday afternoon but by Tuesday afternoon the questions were back and it kept my records in tact. Now it's been since Tuesday afternoon that the screen is just blank for course C191. I take the exam tomorrow and I had plans to do all 717 questions prior to that exam. Is there anyway for someone to fix this issue please. I was learning A LOT using this platform. Videos do not help me learn like multiple choice questions.

**Comment by jmatzen** [comment]
Thanks for letting me know.  The gateway server ran out of disk space.  I also updated the quiz data to the latest version while trying to figure out the issue.

**Comment by kshaw75** [comment]
No problem! THANK YOU for fixing it! I appreciate it!
