### ISSUE TITLE
Bug model

### ISSUE THREAD

**Issue by jbrlhn** [jmatzen/quizsail#9]
https://github.com/jmatzen/quizsail/blob/7c97e074edbda9a7983876032f66cc9a1efb0d87/public/c857.json#L1361

Shouldn't this be true? Got the definition from the video on Lynda.com "What is a bug model?"  A bug model is a predictive model that's often based on both historical data and planned activities throughout the cycle,

**Comment by jmatzen** [comment]
I always felt weird about this one and I agree.   I think what it's expecting to be true is "A bug model predicts how many bugs you should be tracking at any given time" since that's what it says is true in the course content.
